### PR TITLE
Added missing slash-character on s3-auth resource string parsing.

### PR DESCRIPTION
**Pull request by ndob**
More info here:

https://github.com/LearnBoost/knox/pull/210

### CODE REVIEW

**Comment by oppegard** [comment]
Thanks for submitting this pull request!

All pull request authors must have a Contributor License Agreement (CLA) on-file with us. Please sign the appropriate CLA ([individual](http://www.cloudfoundry.org/assets/individualcontribution.pdf) or [corporate](http://www.cloudfoundry.org/assets/corpcontribution.pdf)).

When sending signed CLA please provide your github username in case of individual CLA or the list of github usernames that can make pull requests on behalf of your organization.

Also, can you add a test that exercises the change you made? See the section titled _Testing_ in our [CF Contribution and Code Standards](https://docs.google.com/a/pivotallabs.com/document/d/1SfXFRuxZ2sS16GrYXPEI8Gjd75nNj_Z9xXrTriQSUc0).

**Comment by caseymct** [comment]
@ndob bump re: CLA and test coverage

**Comment by ndob** [comment]
For tests to work, I had to update vows to 0.7. Not sure if this is required, but I couldn't run them otherwise.

As a sidenote: There seems to be a problem in utils.js -> execSync-function. It seems to be hanging on my computer (Ubuntu 13.10 x64, node 0.10.23). I'm not sure if it's just me, so I didn't do anything for it as it's not even used in s3-related tests.

**Comment by ndob** [comment]
Can CLA be sent by post only? Then unfortunately seems too complicated for me. I can also release this piece of code as public domain if you can use it that way. If not, then please just close.

**Comment by jbayer** [comment]
@ndob, you can send an electronic copy (image, PDF, etc) to contributors@cloudfoundry.org

**Comment by dajulia3** [comment]
@ndob, @jbayer have we received the CLA? If not I'd like to close this PR.

Thanks!

**Comment by dajulia3** [comment]
Just checked- we have not received a CLA yet, so I'm closing this PR.
@ndob, please resubmit this PR if you decide to sign the CLA.

Thanks!

**Pull request closed without merging**
